// src/components/Footer.jsx (The Quiet Credits - now more subtle with separated tips)

import React, { useState } from "react";
import proTipsData from "../data/proTips.json";

export function ProTipsSection() {
  const [currentTipIndex, setCurrentTipIndex] = useState(0);
  const proTips = proTipsData.pro_tips;
  const currentTip = proTips[currentTipIndex];

  const nextTip = () => {
    setCurrentTipIndex((prev) => (prev + 1) % proTips.length);
  };

  const prevTip = () => {
    setCurrentTipIndex((prev) => 
      prev === 0 ? proTips.length - 1 : prev - 1
    );
  };

  // 
    // return (
    //   <section className="section">
    //   <div className="footer-tips">
    //       <div className="tip-container">
         //  <button 
    //           className="tip-nav-btn tip-nav-prev"
    //           onClick={prevTip}
    //           aria-label="Previous tip"
     //      >
     //          ‹
     //      </button>
     //      
     //      <div className="tip-content">
     //          <strong>Hot tip:</strong> {currentTip.snippet}{" "}
     //          <a 
     //          href={currentTip.url} 
     //          target="_blank" 
      //         rel="noopener noreferrer"
      //         className="tip-source"
      //      >
     //          {currentTip.article_title}
     //          </a>
     //      </div>
        
     //      <button 
     //          className="tip-nav-btn tip-nav-next"
     //          onClick={nextTip}
      //         aria-label="Next tip"
      //     >
     //          ›
     //      </button>
     //      </div>
     //    </div>
    //   </section>
  //   );
  }

export default function Footer() {
  // Email protection - simple obfuscation
  const getProtectedEmail = () => {
    const user = "hello";
    const domain = "clearconvey.co";
    return `${user}@${domain}`;
  };

  return (
    <footer className="app-footer">
      <div className="footer-content">
        <div className="footer-section">
          <h3>Contact</h3>
          <p>
            Questions or feedback? Reach out at{" "}
            <a 
              href={`mailto:${getProtectedEmail()}`}
              className="footer-link"
            >
              {getProtectedEmail()}
            </a>
          </p>
        </div>

        <div className="footer-section">
          <h3>How it's made</h3>
          <p>
            This site is made with Visual Studio Code, various LLMs, Github, Render and Vercel. 
            Resources referenced in the creation of this tool include public articles from the{" "}
            <a 
              href="https://www.nngroup.com" 
              target="_blank" 
              rel="noopener noreferrer"
              className="footer-link"
            >
              Nielsen Norman Group
            </a>{" "}
            and experience in copywriting across industries and platforms.
          </p>
        </div>

        <div className="footer-section">
          <h3>Disclaimer</h3>
          <p>
            Outputs are generated by an AI language model with prompted guidance based on 
            established web writing principles. Please rely on your own professional judgment 
            when using the generated content. No guarantees are made regarding accuracy, 
            suitability, or effectiveness for your specific use case. Always review and 
            adapt AI-generated content to meet your needs and standards.
          </p>
        </div>
      </div>

      <div className="footer-bottom">
        <p>&copy; 2024 Clear Convey. Made with care for better web writing.</p>
      </div>
    </footer>
  );
}